// Used only for single-bundle builds (INLINE_MODELS=1): models embedded as data URLs.
// @ts-ignore generated by tools/inline-models.mjs
import { MODEL_DATA } from './modelData.gen';
export const modelUrl = (name: string) => (MODEL_DATA as Record<string, string>)[name];
